// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';
import { capacitorStorage } from '@/lib/capacitorStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Basic runtime guard so missing envs are obvious during development
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
	console.error(
		"[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Create a .env file at the project root with:\n" +
		"VITE_SUPABASE_URL=https://YOUR-PROJECT-REF.supabase.co\n" +
		"VITE_SUPABASE_PUBLISHABLE_KEY=YOUR-ANON-PUBLIC-KEY"
	);
}

// Use Capacitor storage on native platforms, localStorage on web
const storage = Capacitor.isNativePlatform() ? capacitorStorage : localStorage;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: storage as any,
    storageKey: 'primeflex-auth-token',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'X-Client-Info': 'primeflex-mobile-app'
    }
  }
});